import matplotlib.pyplot as mplt
mplt.rcParams['font.sans-serif']=['SimHei']
date=['2020/7/21','2020/7/22','2020/7/23']
yue=[10,20,30]
min=[40,50,60]
#z折线图
mplt.plot(date,yue,color='red',label='广东')
mplt.plot(date,min,color='blue',label='福建')
mplt.title('降雨量')
mplt.xlabel('日期')
mplt.ylabel('降雨量')
mplt.legend()
mplt.show()
#柱状图
mplt.bar(date,yue,color='red',label='广东')
mplt.legend()
mplt.show()
#水平柱状图
mplt.barh(date,yue,color='red',label='广东')
mplt.legend()
mplt.show()
#饼图
data=[1,2]
color=['red','blue']
province=['福建','广东']
mplt.pie(x=data,labels=province,colors=color)
mplt.legend()
mplt.show()
